run:
  tests: true
  build-tags:
    - bench
    - !bench
  go: '1.21'

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - "github.com/stretchr/testify/require"
          - "fmt"
          - "time"
          - "golang.org/x/example/hello/reverse"
  funlen:
    lines: 400
    statements: 80
  lll:
    line-length: 200           # максимальная длина строки
    ignore-generated: true     # игнорировать сгенерированные файлы
    ignore-tests: true
  tagliatelle:
    case:
      rules:
        json: camel      # camelCase для JSON
        yaml: camel      # camelCase для YAML
        db: snake        # snake_case для DB
  nolintlint:
    require-explanation: false      # не требовать объяснений
    require-specific: false         # разрешить общий //nolint без указания линтера
    allow-unused: true              # разрешить неиспользуемые директивы

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  enable:
    - asciicheck
    - bodyclose
#    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
